[tool.poetry]
name = "add_sticke"
version = "0.1.0"
description = ""
authors = ["lastwater8725 <chlwhdtn8725@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.14"
altgraph = "0.17.4"
numpy = "2.1.3"
opencv-python = "4.10.0.84"
packaging = "24.1"
pefile = "2023.2.7"
pyinstaller = "6.11.0"
pyinstaller-hooks-contrib = "2024.9"
PyQt6 = "6.7.1"
PyQt6-Qt6 = "6.7.3"
PyQt6_sip = "13.8.0"
pywin32-ctypes = "0.2.3"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
